Algoritmo "areaQuadrado"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   :
// Autor(a)    : Gabriela Nicassio
// Data atual  : 31/05/2021
Var
//lado variavel da entrada
//area variavel do processamento e saida
lado,area : real


Inicio

//entrada
escreval("digite o lado do quadrado: ")
leia(lado)


//processamento
area <- lado*lado

//saida
escreval("A area do quadrado :" ,area)

Fimalgoritmo